[package]
name = "habitat_api_client"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[dependencies]
broadcast = "*"
chrono = "*"
# Pending upgrade activities in https://github.com/habitat-sh/core/issues/72
hyper = "0.10"
hyper-openssl = "*"
log = "*"
pbr = "*"
rand = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tee = "*"
url = "*"

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/core.git"
branch = "cm/clarify-signal-behavior"

[dependencies.habitat_http_client]
git = "https://github.com/habitat-sh/core.git"
branch = "cm/clarify-signal-behavior"
