[package]
name = "habitat-sup-protocol"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "./build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
bytes = "*"
futures = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git", branch = "cm/clarify-signal-behavior" }
lazy_static = "*"
log = "*"
prost = "*"
prost-derive = "*"
rand = "*"
serde = "*"
serde_derive = "*"
tokio = "*"
tokio-codec = "*"

[build-dependencies]
heck = "*"
prost = "*"
prost-build = "*"
prost-types = "*"
tempfile = "*"

[dev-dependencies]
tempfile = "*"
toml = "*"

[features]
default = ["protocols"]
protocols = []
