[package]
name = "habitat-launcher-client"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[dependencies]
bincode = "*"
env_logger = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git", branch = "cm/clarify-signal-behavior" }
habitat-launcher-protocol = { path = "../launcher-protocol" }
habitat_common = { path = "../common" }
ipc-channel = { git = "https://github.com/habitat-sh/ipc-channel", branch = "hbt-windows" }
libc = "*"
log = "*"
prost = "*"
serde = "*"
