[package]
name = "habitat_pkg_export_tar"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[lib]
name = "habitat_pkg_export_tar"

[[bin]]
name = "hab-pkg-export-tar"
path = "src/main.rs"
doc = false

[dependencies]
base64 = "*"
clap = { version = "*", features = ["suggestions", "color", "unstable"] }
env_logger = "*"
hab = { path = "../hab" }
habitat_common = { path = "../common" }
habitat_core = { git = "https://github.com/habitat-sh/core.git", branch = "cm/clarify-signal-behavior" }
# We need to lock here since v0.30.0 bumps to a version of pest that fails to build on Windows.
handlebars = { version = "0.29.1", default-features = false }
lazy_static = "*"
log = "*"
mktemp = "*"
serde = { version = "*", features = ["rc"] }
serde_json = "*"
url = "*"
failure = "*"
failure_derive = "*"
tempfile = "*"
tar = "*"
flate2 = "*"
