[package]
name = "habitat-launcher"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[[bin]]
name = "hab-launch"
path = "src/main.rs"
doc = false

[dependencies]
env_logger = "*"
habitat_common = { path = "../common" }
# JW TODO: core has external deps that we don't want, libarchive/libsodium. We should either
# put these things behind a feature flag so we can statically compile the launcher.
habitat_core = { git = "https://github.com/habitat-sh/core.git", branch = "cm/clarify-signal-behavior" }
habitat-launcher-protocol = { path = "../launcher-protocol" }
ipc-channel = { git = "https://github.com/habitat-sh/ipc-channel", branch = "hbt-windows" }
libc = "*"
log = "*"
prost = "*"
semver = "*"
time = "*"

[target.'cfg(windows)'.dependencies]
winapi =  { version = "*", features = ["tlhelp32"] }
